version: '3.8'

services:
  meshgen:
    build: .
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp
    environment:
      - MESHGEN_STL_FILE=/app/data/Part.stl
      - SHOW_LOGS_IN_CONSOLE=true