services:
  mesh-gen:
    build:  # Usa el Dockerfile para construir la imagen
      context: .  # Usa el directorio actual como contexto
    volumes:
      - .:/mesh-gen  # Monta todo el proyecto

    working_dir: /mesh-gen
    tty: true
