import pickle
import numpy as np
import networkx as nx
from config import config
import os
from utils import split_graph, delaunay_path, distance
import pymesh

class GCodeGen:

    def __init__(self, graph_path, config, **kwargs):
        self.config = config
        self.G = pickle.load(open(graph_path, 'rb'))
        self.output_path = os.path.dirname(graph_path)
        self.file = open(os.path.join(self.output_path, "graph.gcode"), 'w')
        self.__set_origin()
        self.current_point = (0,0,0)
        self.extrusion = 0
        self.z_offset = self.config.printing.LAYERHEIGHT * (self.config.printing.BOTTOMLAYERS - 1)
        self.__start_gcode()
        
        self.main()

        self.__end_gcode()
        self.file.close()

    def __start_gcode(self):
        self.file.write("G21    ;set units to millimeters\n")
        self.file.write("G90    ;use absolute coordinates\n")
        self.file.write("G92 E0    ;reset extruder position\n")
        self.file.write("G28    ;home all axes\n")
        self.file.write("M92 E424.9    ;Set Esteps\n")
        self.file.write("M500    ;Store settings\n")
        # self.file.write("M83    ;use relative distances for extrusion\n")
        self.file.write(f"M190 S{self.config.printing.BEDTEMP}    ;set bed temperature to 60 and wait\n")
        self.file.write(f"M109 S{self.config.printing.EXTRUDERTEMP}    ;set extruder temperature to 200 and wait\n")
        self.file.write(f"G0 X5 Y5 Z{self.config.printing.LAYERHEIGHT}\n")
        self.file.write("G1 F600\n")
        self.file.write("G1 Y150 E{:.3f}\n".format(self.__extrusion(145)))
        self.file.write("G1 Y5 E{:.3f}\n".format(self.__extrusion(145)))
        self.file.write("G0 X{:.3f} Y{:.3f} Z{:.3f} F9000    ;move to origin\n".format(self.X_origin, 
                                                                                       self.Y_origin, 
                                                                                       self.Z_origin)) #Move to origin
        self.file.write("G92 X0 Y0 Z0    ;set current position as origin\n")

    def __end_gcode(self):
        self.file.write("G91 \n")
        self.file.write("G1 E-2 F2700\n")
        self.file.write("G1 Z1 E-2 F2400 ;raise the extruder 1 cm\n".format(self.config.printing.LAYERHEIGHT))
        self.file.write(f"G0 X{-self.X_origin}    ;move to the initial point\n")
        # self.file.write("M104 S0    ;turn off the extruder\n")
        # self.file.write("M140 S0    ;turn off the bed\n")
        # self.file.write("M106 S0    ;turn off the fan\n")
        self.file.write("M84    ;disable motors\n")
        
    def __set_origin(self):
        self.X_origin = self.config.printing.BEDDIMENSIONS[0] / 2
        self.Y_origin = self.config.printing.BEDDIMENSIONS[1] / 2
        self.Z_origin = self.config.printing.LAYERHEIGHT
    
    def main(self):
        self.base, self.top, self.sorted_nodles = split_graph(self.G)

        self.__write_base_path()

        self.file.write("G1 F{:.3f}\n".format(self.config.printing.NO_PLANAR_FEEDRATE))

        self.queue = self.printing_queue()
        a = []
        for n in self.queue:
            if n[2] != 60:
                a.append(n)
        
        # for node in self.queue:
        self.first = True
        for node in a:
            polyhedron_path = self.base_nodes(node)
            self.__write_polihedron_path(polyhedron_path)
    
        # self.__write_top_path()

    def __write_base_path(self):
        """
        Write the G-code instructions to print the base. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        self.file.write("; start base printing\n")
        initial_point = list(self.base)[0]
        path = delaunay_path(self.base, initial_point)
        for z in range(self.config.printing.BOTTOMLAYERS):
            z_layer = initial_point[2] + z * self.config.printing.LAYERHEIGHT 
            self.__move_to_point_2d((initial_point[0], initial_point[1], z_layer), 5,5)
            self.file.write("G0 F600\n")
            self.current_point = initial_point
            for edge in path:
                if edge[0] == self.current_point:
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer,
                                                                                  self.__extrusion(edge[0], edge[1], FR = 0.5)))
                else:
                    self.__move_to_point_2d(np.array(edge[0]) + np.array([0,0, z_layer]), 5,5)
                    self.file.write("G0 F600\n")
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1], FR = 0.5)))

                self.current_point = edge[1]

        for i in self.base:
            point_with_offset = np.array(i) + np.array([0,0, self.config.printing.BOTTOMLAYERS*self.z_offset + self.config.printing.OUTTER_RADIUS])
            self.__move_to_point(point_with_offset, 5,5)
            self.extrusion += 3.5 # 3.5mm of over extrusion for semi-sphere of 0.55mm radius
            self.file.write("G1 E{:.3f} F{:.3f}\n".format(self.extrusion, self.config.printing.NO_PLANAR_FEEDRATE))
            self.current_point = point_with_offset


    def __write_top_path(self):
        """
        Write the G-code instructions to print the base. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        self.file.write("; start top printing\n")
        initial_point = self.queue[-1]
        path = delaunay_path(self.top, initial_point)
        for z in range(self.config.printing.TOPLAYERS):
            z_layer = initial_point[2] + z * self.config.printing.LAYERHEIGHT 
            self.__move_to_point((initial_point[0], initial_point[1], z_layer), 10, 10)
            self.current_point = initial_point
            for edge in path:
                if edge[0] == self.current_point:
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))
                else:
                    self.__move_to_point(np.array(edge[0]) + np.array([0,0,  z * self.config.printing.LAYERHEIGHT]), 10,10)
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))

                self.current_point = edge[1]

    def __write_polihedron_path(self, polyhedron_path):
        """
        Write the G-code instructions to print the polyhedron. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        for it, (base, apex) in enumerate(polyhedron_path):

            adapt_base = self.calculate_base(base, apex) + np.array([0,0, self.z_offset])
            # if not self.first:
            self.__move_to_point(adapt_base, 10)
            self.file.write("G4 S10  ;Espeo 10 segundos\n")
            self.file.write("M400 \n")
            adapt_apex = self.calculate_apex(adapt_base, apex + np.array([0,0, self.z_offset]))
            self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f} F{:.3F}\n".format(adapt_apex[0], 
                                                                          adapt_apex[1], 
                                                                          adapt_apex[2], 
                                                                          self.__extrusion(adapt_base, adapt_apex, 0.5),
                                                                    self.config.printing.NO_PLANAR_FEEDRATE))
            self.current_point = adapt_apex
            self.first = False 
        
        # self.__move_to_point(apex + np.array([0,0,self.z_offset]), 10, 10)

        # self.extrusion += 1
        # self.file.write("G0 E{:.3f} F500 \n".format(self.extrusion))

    def __move_to_point(self, point, retraction_height = 10, retraction = 0, over_extrusion = 0.5):
        """
        Move the extruder to a given point. The extruder is raised by 
        retraction_height mm before moving to the point. The extruder 
        moves in the XY plane to the point and then goes down to the
        Z coordinate of the point.
        """
        self.extrusion -= retraction
        # self.file.write(f"M117 Subo    \n")
        self.file.write("G4 S5  ;Espeo 5 segundos\n")
        self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} F600 E{:.3f}\n".format(self.current_point[0],
                                                                            self.current_point[1],
                                                                            self.current_point[2]+ retraction_height,
                                                                            self.extrusion))                                                           
        # self.file.write("G4 S5  ;Espeo 5 segundos\n")
        
        self.file.write(f"M117 Muevo a {point[0], point[1]}     \n")
        self.file.write("G0 X{:.3f} Y{:.3f} F2000\n".format(point[0], point[1]))
        self.file.write(f"M117 Bajo a {point[0]}    \n")
        self.file.write("G0 Z{:.3f} F600\n".format(point[2]))
        self.extrusion += retraction + over_extrusion
        self.file.write(f"M117 Extrusion {self.extrusion}    ;\n")
        self.file.write("G0 E{:.3f} F600\n".format(self.extrusion))
        self.file.write("M400\n")
        self.current_point = point

    def __move_to_point_2d(self, point, retraction_height = 5, retraction = 10):
        """
        Move the extruder to a given point. The extruder is raised by 
        retraction_height mm before moving to the point. The extruder 
        moves in the XY plane to the point and then goes down to the
        Z coordinate of the point.
        """
        self.extrusion -= retraction
        # self.file.write(f"M117 Subo    \n")
        # self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} F600 E{:.3f}\n".format(self.current_point[0],
        #                                                                     self.current_point[1],
        #                                                                     self.current_point[2]+ retraction_height,
        #                                                                     self.extrusion))  
 
        mid_point = (np.array(point) + np.array(self.current_point))/2 + np.array([0,0,self.config.printing.LAYERHEIGHT])             

        self.file.write("G0 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(mid_point[0], mid_point[1], mid_point[2], self.extrusion))
        self.extrusion += retraction
    
        self.file.write("G0 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(point[0], point[1], point[2], self.extrusion))
        # self.file.write("G0 Z{:.3f} F600\n".format(point[2]))
        # self.file.write(f"M117 Extrusion {self.extrusion}    ;\n")
        # self.file.write("G0 E{:.3f} \n".format(self.extrusion))
        # self.file.write("M400\n")
        self.current_point = point


    def printing_queue(self):
        return list(filter( lambda x: x[2] != 0, sorted(list(self.G),
                                                        key = lambda x: x[2])))
    
    def base_nodes(self, node):
        base_path = []
        base = sorted(filter(lambda x: x[2] < node[2], 
                             list(self.G.neighbors(node))), 
                      key= lambda x: distance(x,node))
        for base_node in base:
            base_path.append((base_node, node))
        
        return base_path
    
    def calculate_apex(self, base, apex):

        m1 = pymesh.generate_cylinder(base, apex, 0.4, 0.4)
        m2 = pymesh.generate_icosphere(0.5, apex)
        intersect = pymesh.boolean(m1,m2, "intersection").vertices
        min_intersect = intersect[np.argmin(intersect[:,2])]
        L = np.linalg.norm(apex-base)
        x2p = apex - np.linalg.norm(min_intersect - apex)/L * (apex - base)

        return x2p
    
    def calculate_base(self, base, apex):
        base = base + np.array([0,0, self.z_offset])
        m1 = pymesh.generate_cylinder(base, apex, 0.4, 0.4)
        m2 = pymesh.generate_icosphere(0.5, base)
        intersect = pymesh.boolean(m1,m2, "intersection").vertices
        max_intersect = max(intersect, key=lambda x: x[2])

        return np.array(max_intersect)

    def __extrusion(self, pnt1, pnt2 = None, FR = 1):
        """
        Calculate the extrusion distance given the distance to move the extruder.
        The extrusion distance is calculated as the distance to move the extruder
        multiplied by the extrusion width.
        """
        if pnt2 is None:
            distance = np.linalg.norm(np.array(pnt1))
        else:
            distance = np.linalg.norm(np.array(pnt2) - np.array(pnt1))

        self.extrusion += FR*(self.config.printing.EXTRUSIONWIDTH/self.config.printing.FILAMENTWIDTH)**2 * distance

        return self.extrusion
    
if __name__ == "__main__":
    GCodeGen("/home/alex/Downloads/one_layer/G_2.pickle", config)