import pickle
import numpy as np
import networkx as nx
import config
import os
from utils import split_graph, delaunay_path, distance

class GCodeGen:

    def __init__(self, graph_path, **kwargs):
        
        self.G = pickle.load(open(graph_path, 'rb'))
        self.output_path = os.path.dirname(graph_path)
        self.file = open(os.path.join(self.output_path, "graph.gcode"), 'w')
        self.__set_origin()
        self.z_offset = config.LAYERHEIGHT * (config.BOTTOMLAYERS - 1)
        self.__start_gcode()
        
        self.main()

        self.__end_gcode()
        self.file.close()

    def __start_gcode(self):
        self.file.write("G21    ;set units to millimeters\n")
        self.file.write("G90    ;use absolute coordinates\n")
        self.file.write("G92 E0    ;reset extruder position\n")
        self.file.write("G28    ;home all axes\n")
        self.file.write("M83    ;use relative distances for extrusion\n")
        self.file.write(f"M190 S{config.BEDTEMP}    ;set bed temperature to 60 and wait\n")
        self.file.write(f"M109 S{config.EXTRUDERTEMP}    ;set extruder temperature to 200 and wait\n")
        self.file.write(f"G0 X5 Y5 Z{config.LAYERHEIGHT}\n")
        self.file.write("G1 F600\n")
        self.file.write("G1 Y150 E{:.3f}\n".format(self.__extrusion(145)))
        self.file.write("G1 Y5 E{:.3f}\n".format(self.__extrusion(145)))
        self.file.write("G0 X{:.3f} Y{:.3f} Z{:.3f} F9000    ;move to origin\n".format(self.X_origin, 
                                                                                       self.Y_origin, 
                                                                                       self.Z_origin)) #Move to origin
        self.file.write("G92 X0 Y0 Z0    ;set current position as origin\n")

    def __end_gcode(self):
        self.file.write("G1 E-1 F600\n")
        self.file.write("G91 \n")
        self.file.write("G1 Z10 E-5  ;raise the extruder 1 cm\n".format(config.LAYERHEIGHT))
        self.file.write(f"G0 X{-self.X_origin}    ;move to the initial point\n")
        self.file.write("M104 S0    ;turn off the extruder\n")
        self.file.write("M140 S0    ;turn off the bed\n")
        self.file.write("M84    ;disable motors\n")
        
    def __set_origin(self):
        self.X_origin = config.BEDDIMENSIONS[0] / 2
        self.Y_origin = config.BEDDIMENSIONS[1] / 2
        self.Z_origin = config.LAYERHEIGHT
    
    def main(self):
        self.base, self.top, self.sorted_nodles = split_graph(self.G)
        self.__write_base_path()

        self.file.write("G1 F{:.3f}\n".format(config.NO_PLANAR_FEEDRATE))

        self.queue = self.printing_queue()
        for node in self.queue:
            polyhedron_path = self.base_nodes(node)
            self.__write_polihedron_path(polyhedron_path)
    
        self.__write_top_path()

    def __write_base_path(self):
        """
        Write the G-code instructions to print the base. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        self.file.write("; start base printing\n")
        current_node = initial_point = list(self.base)[0]
        path = delaunay_path(self.base, current_node)
        for z in range(config.BOTTOMLAYERS):
            z_layer = current_node[2] + z * config.LAYERHEIGHT 
            self.__move_to_point((initial_point[0], initial_point[1], z_layer), 0.5)

            for edge in path:
                if edge[0] == current_node:
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))
                else:
                    self.__move_to_point(np.array(edge[0]) + np.array([0,0, z_layer]), 0.5)
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))

                current_node = edge[1]

    def __write_top_path(self):
        """
        Write the G-code instructions to print the base. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        self.file.write("; start top printing\n")
        current_node = initial_point = self.queue[-1]
        path = delaunay_path(self.top, current_node)
        for z in range(config.TOPLAYERS):
            z_layer = initial_point[2] + z * config.LAYERHEIGHT 
            self.__move_to_point((initial_point[0], initial_point[1], z_layer), 0.5)

            for edge in path:
                if edge[0] == current_node:
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))
                else:
                    self.__move_to_point(np.array(edge[0]) + np.array([0,0,  z * config.LAYERHEIGHT]), 0.5)
                    self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(edge[1][0], 
                                                                                  edge[1][1], 
                                                                                  z_layer, 
                                                                                  self.__extrusion(edge[0], edge[1])))

                current_node = edge[1]

    def __write_polihedron_path(self, polyhedron_path):
        """
        Write the G-code instructions to print the polyhedron. It follows the path 
        generated by the delaunay_path method. If the next edge to be printed is 
        not contiguous to the previous one, the extruder moves to the first point 
        on the edge and prints the edge.
        """
        for base, apex in polyhedron_path:
            self.__move_to_point((base[0], base[1], base[2] + self.z_offset))
            self.file.write("G1 X{:.3f} Y{:.3f} Z{:.3f} E{:.3f}\n".format(apex[0], 
                                                                          apex[1], 
                                                                          apex[2] + self.z_offset, 
                                                                          self.__extrusion(base, apex)))
    def __move_to_point(self, point, retraction_height = 1):
        """
        Move the extruder to a given point. The extruder is raised by 
        retraction_height mm before moving to the point. The extruder 
        moves in the XY plane to the point and then goes down to the
        Z coordinate of the point.
        """

        self.file.write("G91    ;set relative coords\n")
        self.file.write("G0 Z{:.3f}  ;raise the extruder {} mm\n".format(retraction_height, retraction_height))
        self.file.write("G90    ;set absolute coords\n")
        self.file.write("G0 X{:.3f} Y{:.3f}    ;move above the initial point\n".format(point[0], point[1]))
        self.file.write("G0 Z{:.3f}    ;go down to the initial point\n".format(point[2]))


    def printing_queue(self):
        return list(filter( lambda x: x[2] != 0, sorted(list(self.G),
                                                        key = lambda x: x[2])))
    
    def base_nodes(self, node):
        base_path = []
        base = sorted(filter(lambda x: x[2] < node[2], 
                             list(self.G.neighbors(node))), 
                      key= lambda x: distance(x,node))
        for base_node in base:
            base_path.append((base_node, node))
        
        return base_path
    

    def __extrusion(self, pnt1, pnt2 = None):
        """
        Calculate the extrusion distance given the distance to move the extruder.
        The extrusion distance is calculated as the distance to move the extruder
        multiplied by the extrusion width.
        """
        if pnt2 is None:
            distance = np.linalg.norm(np.array(pnt1))
        else:
            distance = np.linalg.norm(np.array(pnt2) - np.array(pnt1))

        return (config.EXTRUSIONWIDTH/config.FILAMENTWIDTH)**2 * distance
    
if __name__ == "__main__":
    GCodeGen("/home/alex/Desktop/mesh-gen/data/output/Cylinder_21-05-17-17/G.pickle")